package plugin

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/grafana/grafana-plugin-sdk-go/backend/log"
)

// RunStatus represents the current status of a run
type RunStatus string

const (
	RunStatusPending    RunStatus = "pending"
	RunStatusPlanning   RunStatus = "planning"
	RunStatusExecuting  RunStatus = "executing"
	RunStatusPaused     RunStatus = "paused"
	RunStatusCompleted  RunStatus = "completed"
	RunStatusCancelled  RunStatus = "cancelled"
	RunStatusFailed     RunStatus = "failed"
)

// RunState represents the state of a single run
type RunState struct {
	RunID            string
	ConversationID   string
	UserLogin        string
	Status           RunStatus
	Plan             *ExecutionPlan
	CurrentStepIndex int
	Artifacts        []Artifact
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CancelCtx        context.Context
	CancelFunc       context.CancelFunc
	EventChan        chan RunEvent
	pauseChan        chan bool     // For pause/resume signaling
	mu               sync.RWMutex
}

// ExecutionPlan represents the plan generated by the LLM
type ExecutionPlan struct {
	Goal              string        `json:"goal"`
	Steps             []PlannedStep `json:"steps"`
	EstimatedDuration string        `json:"estimatedDuration"`
}

// PlannedStep represents a single step in the execution plan
type PlannedStep struct {
	Index       int    `json:"index"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"` // "pending" | "in_progress" | "completed" | "failed"
}

// Artifact represents evidence collected during execution
type Artifact struct {
	ID        string                 `json:"id"`
	Type      string                 `json:"type"` // "query" | "link" | "trace_id" | "dashboard_link"
	Content   string                 `json:"content"`
	Metadata  map[string]interface{} `json:"metadata"`
	Timestamp time.Time              `json:"timestamp"`
}

// RunManager manages all active runs
type RunManager struct {
	runs          map[string]*RunState
	mu            sync.RWMutex
	logger        log.Logger
	cleanupTicker *time.Ticker
	stopCleanup   chan bool
}

// NewRunManager creates a new RunManager
func NewRunManager(logger log.Logger) *RunManager {
	rm := &RunManager{
		runs:          make(map[string]*RunState),
		logger:        logger,
		cleanupTicker: time.NewTicker(10 * time.Minute),
		stopCleanup:   make(chan bool),
	}

	// Start background cleanup goroutine
	go rm.cleanupRoutine()

	return rm
}

// CreateRun creates a new run and returns its state
// The sourceCtx should contain plugin metadata (PluginContext, GrafanaConfig) which will be preserved
func (rm *RunManager) CreateRun(sourceCtx context.Context, conversationID, userLogin string) (*RunState, error) {
	runID := generateRunID()

	// Create a detached context that preserves plugin metadata but is NOT canceled
	// when sourceCtx (HTTP request) is canceled. This allows the run to continue
	// independently while keeping user identity and auth info.
	detachedCtx := context.WithoutCancel(sourceCtx)

	// Now create a cancelable context from the detached one
	// This can be canceled via CancelRun() but won't be affected by HTTP request lifecycle
	ctx, cancel := context.WithCancel(detachedCtx)

	run := &RunState{
		RunID:          runID,
		ConversationID: conversationID,
		UserLogin:      userLogin,
		Status:         RunStatusPending,
		Artifacts:      []Artifact{},
		CreatedAt:      time.Now().UTC(),
		UpdatedAt:      time.Now().UTC(),
		CancelCtx:      ctx,
		CancelFunc:     cancel,
		EventChan:      make(chan RunEvent, 100), // Buffered channel
		pauseChan:      make(chan bool, 1),
	}

	rm.mu.Lock()
	rm.runs[runID] = run
	rm.mu.Unlock()

	rm.logger.Info("Run created", "runId", runID, "conversationId", conversationID, "user", userLogin)

	return run, nil
}

// GetRun retrieves a run by ID
func (rm *RunManager) GetRun(runID string) (*RunState, error) {
	rm.mu.RLock()
	run, exists := rm.runs[runID]
	rm.mu.RUnlock()

	if !exists {
		return nil, fmt.Errorf("run not found: %s", runID)
	}

	return run, nil
}

// UpdateRunStatus updates the status of a run
func (rm *RunManager) UpdateRunStatus(runID string, status RunStatus) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	run.Status = status
	run.UpdatedAt = time.Now().UTC()
	run.mu.Unlock()

	rm.logger.Debug("Run status updated", "runId", runID, "status", status)

	return nil
}

// SetPlan sets the execution plan for a run
func (rm *RunManager) SetPlan(runID string, plan *ExecutionPlan) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	run.Plan = plan
	run.UpdatedAt = time.Now().UTC()
	run.mu.Unlock()

	rm.logger.Info("Execution plan set", "runId", runID, "stepCount", len(plan.Steps))

	return nil
}

// AddArtifact adds an artifact to a run
func (rm *RunManager) AddArtifact(runID string, artifact Artifact) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	run.Artifacts = append(run.Artifacts, artifact)
	run.UpdatedAt = time.Now().UTC()
	run.mu.Unlock()

	rm.logger.Debug("Artifact added", "runId", runID, "artifactId", artifact.ID, "type", artifact.Type)

	return nil
}

// UpdateStepStatus updates the status of a specific step
func (rm *RunManager) UpdateStepStatus(runID string, stepIndex int, status string) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	defer run.mu.Unlock()

	if run.Plan == nil || stepIndex >= len(run.Plan.Steps) {
		return fmt.Errorf("invalid step index: %d", stepIndex)
	}

	run.Plan.Steps[stepIndex].Status = status
	run.CurrentStepIndex = stepIndex
	run.UpdatedAt = time.Now().UTC()

	return nil
}

// PauseRun pauses a run's execution
func (rm *RunManager) PauseRun(runID string) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	currentStatus := run.Status
	run.mu.Unlock()

	// Only allow pausing if executing
	if currentStatus != RunStatusExecuting {
		return fmt.Errorf("cannot pause run in status: %s", currentStatus)
	}

	// Update status
	if err := rm.UpdateRunStatus(runID, RunStatusPaused); err != nil {
		return err
	}

	rm.logger.Info("Run paused", "runId", runID)

	return nil
}

// ResumeRun resumes a paused run
func (rm *RunManager) ResumeRun(runID string) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	currentStatus := run.Status
	run.mu.Unlock()

	// Only allow resuming if paused
	if currentStatus != RunStatusPaused {
		return fmt.Errorf("cannot resume run in status: %s", currentStatus)
	}

	// Update status
	if err := rm.UpdateRunStatus(runID, RunStatusExecuting); err != nil {
		return err
	}

	// Signal resume
	select {
	case run.pauseChan <- true:
	default:
	}

	rm.logger.Info("Run resumed", "runId", runID)

	return nil
}

// CancelRun cancels a run and cleans up resources
func (rm *RunManager) CancelRun(runID string) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	run.mu.Lock()
	currentStatus := run.Status
	run.mu.Unlock()

	// Don't cancel if already completed/cancelled/failed
	if currentStatus == RunStatusCompleted || currentStatus == RunStatusCancelled || currentStatus == RunStatusFailed {
		return fmt.Errorf("cannot cancel run in status: %s", currentStatus)
	}

	// Trigger cancellation context
	run.CancelFunc()

	// Update status
	if err := rm.UpdateRunStatus(runID, RunStatusCancelled); err != nil {
		return err
	}

	rm.logger.Info("Run cancelled", "runId", runID)

	return nil
}

// CheckPauseOrCancel checks if run should pause or has been cancelled
// Returns: shouldContinue bool, wasPaused bool
func (rm *RunManager) CheckPauseOrCancel(runID string) (bool, bool) {
	run, err := rm.GetRun(runID)
	if err != nil {
		return false, false
	}

	// Check cancellation
	select {
	case <-run.CancelCtx.Done():
		return false, false
	default:
	}

	// Check pause
	run.mu.RLock()
	status := run.Status
	run.mu.RUnlock()

	if status == RunStatusPaused {
		// Wait for resume signal
		select {
		case <-run.pauseChan:
			return true, true
		case <-run.CancelCtx.Done():
			return false, true
		case <-time.After(1 * time.Hour): // Timeout after 1 hour
			rm.logger.Warn("Pause timeout exceeded", "runId", runID)
			return false, true
		}
	}

	return true, false
}

// CloseEventChannel closes the event channel for a run
func (rm *RunManager) CloseEventChannel(runID string) error {
	run, err := rm.GetRun(runID)
	if err != nil {
		return err
	}

	close(run.EventChan)
	rm.logger.Debug("Event channel closed", "runId", runID)

	return nil
}

// CleanupRun removes a run from the manager
func (rm *RunManager) CleanupRun(runID string) error {
	rm.mu.Lock()
	defer rm.mu.Unlock()

	run, exists := rm.runs[runID]
	if !exists {
		return fmt.Errorf("run not found: %s", runID)
	}

	// Cancel context if not already cancelled
	run.CancelFunc()

	// Remove from map
	delete(rm.runs, runID)

	rm.logger.Info("Run cleaned up", "runId", runID)

	return nil
}

// cleanupRoutine periodically cleans up old completed runs
func (rm *RunManager) cleanupRoutine() {
	for {
		select {
		case <-rm.cleanupTicker.C:
			rm.cleanupOldRuns()
		case <-rm.stopCleanup:
			rm.cleanupTicker.Stop()
			return
		}
	}
}

// cleanupOldRuns removes runs older than 1 hour that are completed/cancelled/failed
func (rm *RunManager) cleanupOldRuns() {
	now := time.Now().UTC()
	threshold := 1 * time.Hour

	rm.mu.Lock()
	defer rm.mu.Unlock()

	for runID, run := range rm.runs {
		run.mu.RLock()
		status := run.Status
		updatedAt := run.UpdatedAt
		run.mu.RUnlock()

		// Check if run is in terminal state and older than threshold
		if (status == RunStatusCompleted || status == RunStatusCancelled || status == RunStatusFailed) &&
			now.Sub(updatedAt) > threshold {

			// Cancel context
			run.CancelFunc()

			// Remove from map
			delete(rm.runs, runID)

			rm.logger.Info("Run auto-cleaned", "runId", runID, "status", status, "age", now.Sub(updatedAt))
		}
	}
}

// GetRunCount returns the number of active runs
func (rm *RunManager) GetRunCount() int {
	rm.mu.RLock()
	defer rm.mu.RUnlock()
	return len(rm.runs)
}

// GetUserRunCount returns the number of active runs for a specific user
func (rm *RunManager) GetUserRunCount(userLogin string) int {
	rm.mu.RLock()
	defer rm.mu.RUnlock()

	count := 0
	for _, run := range rm.runs {
		run.mu.RLock()
		if run.UserLogin == userLogin {
			count++
		}
		run.mu.RUnlock()
	}

	return count
}

// Stop stops the run manager and cleans up resources
func (rm *RunManager) Stop() {
	rm.stopCleanup <- true

	// Cancel all active runs
	rm.mu.Lock()
	for _, run := range rm.runs {
		run.CancelFunc()
	}
	rm.mu.Unlock()

	rm.logger.Info("RunManager stopped")
}

// generateRunID generates a unique run ID
func generateRunID() string {
	return fmt.Sprintf("run_%s", uuid.New().String())
}
